package dds.grupo3.clases.tipoDeMediciones;

public enum TipoDeConsumo {	
	GAS_NATURAL, DIESEL_GASOIL, KEROSENE, FUEL_OIL, NAFTA, CARBON, CARBON_DE_LENIA, LENIA, ELECTRICIDAD, REACTIVO_MEDICINA, REACTIVO_ENERGETICO, AGUA_PESADA

}
